# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publikationen"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "https://blog.sandra-parsick.de"
  weight = 3

[[menu.main]]
  name = "Projekte"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Kontakt"
  url = "#contact"
  weight = 5

[[menu.main]]
  name = "Impressum"
  url = "impressum"
  weight = 6

[[menu.main]]
  name = "Datenschutzerklärung"
  url = "datenschutzerklaerung"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
